### ISSUE TITLE
`Api::V1::ExceptionsHandler#handle_api_error` eats underlying Exceptions

### ISSUE THREAD

**Issue by seattlecyclist** [bullet-train-co/bullet_train-api#13]
If there is an exception the underlying exception does not get dumped to stdout such that the developer can see what a root failure was.  Rather they are presented with a generic exception that masquerades the root cause.

To reproduce, follow the steps in this ticket:  https://github.com/bullet-train-co/bullet_train-api/issues/11.

**Comment by gazayas** [comment]
Thanks for reporting, I'm pretty sure this came up before the Great Unbundling, but we haven't addressed it yet in this repository.
